# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Your Macs as a private build/agent cloud: Tart VMs via Orchard, jobs via Nomad."
  homepage "https://github.com/gm2211/grove"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gm2211/grove/releases/download/v0.1.4/grove_darwin_amd64.tar.gz"
      sha256 "13e8e39335b15b41549afa1c08207392ae6faed075973171f3adbead5ff182d8"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gm2211/grove/releases/download/v0.1.4/grove_darwin_arm64.tar.gz"
      sha256 "2cd116f1249931bf201fa854bf34955a8a29679c469b51d39ee13abf9a7812bd"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gm2211/grove/releases/download/v0.1.4/grove_linux_amd64.tar.gz"
      sha256 "c43ecc026ab071aac5fecd5939ca26059d4b824b8565ff06f99b6bb4ade5473a"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gm2211/grove/releases/download/v0.1.4/grove_linux_arm64.tar.gz"
      sha256 "c759b56bf3c26beff131466f4fafc0d83ead5864c54e1661f140e2b89d19d010"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  def caveats
    <<~EOS
      Grove's binary is installed. To join this Mac to an existing Grove cluster, run:

        grove setup

      Setup discovers the control plane over Tailscale, requests operator approval, installs
      the worker service, and verifies that the worker is visible.
    EOS
  end

  test do
    system "#{bin}/grove", "--version"
  end
end
