# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Your Macs as a private build/agent cloud: Tart VMs via Orchard, jobs via Nomad."
  homepage "https://github.com/gm2211/grove"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gm2211/grove/releases/download/v0.1.11/grove_darwin_amd64.tar.gz"
      sha256 "78a87697008c39f3beddaf41f7fc1f3661eb6396c6760a56ece38462198ba281"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gm2211/grove/releases/download/v0.1.11/grove_darwin_arm64.tar.gz"
      sha256 "b39de981c813a3805e5fa6efcf39e4c65f8bb9fd9d336318a12a434f6ea8ffaf"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gm2211/grove/releases/download/v0.1.11/grove_linux_amd64.tar.gz"
      sha256 "9555656f11deabace5203a87e4aebab96cfbbfc9c2d1d653370f47d425cb56bc"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gm2211/grove/releases/download/v0.1.11/grove_linux_arm64.tar.gz"
      sha256 "19fae7f97e6f712d379e597eda1eff2db14b6be7a2f437291df6d26d56d9bbad"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  def caveats
    <<~EOS
      Grove's binary is installed. To join this Mac to an existing Grove cluster, run:

        grove setup

      Setup discovers the control plane over Tailscale, requests operator approval, installs
      the worker service, and verifies that the worker is visible.
    EOS
  end

  test do
    system "#{bin}/grove", "--version"
  end
end
