# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Your Macs as a private build/agent cloud: Tart VMs via Orchard, jobs via Nomad."
  homepage "https://github.com/gm2211/grove"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gm2211/grove/releases/download/v0.1.5/grove_darwin_amd64.tar.gz"
      sha256 "fe8690cc6e03213bf8474f1fd820b73b5c612459da728aff52910e3d0bfc4a8b"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gm2211/grove/releases/download/v0.1.5/grove_darwin_arm64.tar.gz"
      sha256 "6fc8427ce488c352f81d47445a138b51f9a190288ef36d0b47cda2e311838b6e"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gm2211/grove/releases/download/v0.1.5/grove_linux_amd64.tar.gz"
      sha256 "70a1d6dc045e334c4ebbb4b3c1c9d56d4fc78fe9df697da0d16296edd1e50bbd"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gm2211/grove/releases/download/v0.1.5/grove_linux_arm64.tar.gz"
      sha256 "eb6e7a28fb61510b9d7b8d456cb15e2b30f69e19765a7759379ce0f811f1a360"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  def caveats
    <<~EOS
      Grove's binary is installed. To join this Mac to an existing Grove cluster, run:

        grove setup

      Setup discovers the control plane over Tailscale, requests operator approval, installs
      the worker service, and verifies that the worker is visible.
    EOS
  end

  test do
    system "#{bin}/grove", "--version"
  end
end
